-- SmartClass AC / Supabase PostgreSQL setup
-- Run this entire file in Supabase Dashboard -> SQL Editor -> New query.
--
-- This is intentionally server-only storage. Do not add the database password
-- to browser code, and do not use the anon key to query these tables.
-- The SmartClass AC server connects with Npgsql and creates the default admin
-- using the PBKDF2 password hash configured in User Secrets.

begin;

create extension if not exists btree_gist;

create table if not exists public.user_accounts (
    id bigint generated by default as identity primary key,
    username varchar(100) not null,
    display_name varchar(160) not null,
    email varchar(254),
    phone varchar(40),
    password_hash varchar(512) not null,
    role varchar(16) not null check (role in ('Admin', 'Teacher')),
    is_default_admin boolean not null default false,
    is_active boolean not null default true,
    created_utc timestamptz not null default current_timestamp,
    updated_utc timestamptz not null default current_timestamp
);

alter table public.user_accounts add column if not exists phone varchar(40);
create unique index if not exists uq_user_accounts_username_ci on public.user_accounts (lower(username));
create unique index if not exists uq_user_accounts_email_ci on public.user_accounts (lower(email)) where email is not null;
create unique index if not exists uq_user_accounts_default_admin on public.user_accounts (is_default_admin) where is_default_admin;

create table if not exists public.classrooms (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    capacity integer not null check (capacity between 1 and 1000),
    target_temperature integer not null default 22 check (target_temperature between 16 and 30),
    current_temperature numeric(4,1),
    ac_status varchar(24) not null default 'Idle',
    is_active boolean not null default true,
    created_utc timestamptz not null default current_timestamp,
    updated_utc timestamptz not null default current_timestamp
);

create unique index if not exists uq_classrooms_name_ci on public.classrooms (lower(name));

create table if not exists public.fingerprint_templates (
    id bigint generated by default as identity primary key,
    user_account_id bigint not null references public.user_accounts(id) on delete cascade,
    finger_position varchar(32) not null,
    template_identifier uuid not null,
    created_utc timestamptz not null default current_timestamp,
    constraint uq_fingerprint_templates_identifier unique (template_identifier),
    constraint uq_fingerprint_templates_user_finger unique (user_account_id, finger_position)
);

create table if not exists public.password_reset_tokens (
    id bigint generated by default as identity primary key,
    user_account_id bigint not null references public.user_accounts(id) on delete cascade,
    token_hash char(64) not null unique,
    expires_utc timestamptz not null,
    used_utc timestamptz,
    created_utc timestamptz not null default current_timestamp
);

create index if not exists ix_password_reset_tokens_account_expiry
on public.password_reset_tokens (user_account_id, expires_utc desc);

create table if not exists public.class_schedules (
    id bigint generated by default as identity primary key,
    teacher_account_id bigint not null references public.user_accounts(id) on delete cascade,
    original_teacher_account_id bigint references public.user_accounts(id) on delete cascade,
    classroom_id bigint references public.classrooms(id) on delete restrict,
    classroom_name varchar(100) not null,
    subject_name varchar(160) not null default 'Scheduled Class',
    schedule_date date not null,
    start_time time not null,
    end_time time not null,
    created_utc timestamptz not null default current_timestamp,
    updated_utc timestamptz not null default current_timestamp,
    constraint ck_class_schedules_time_range check (end_time > start_time)
);

-- Compatible with the earlier database version that used only classroom_name.
alter table public.class_schedules add column if not exists original_teacher_account_id bigint references public.user_accounts(id) on delete cascade;
alter table public.class_schedules add column if not exists classroom_id bigint references public.classrooms(id) on delete restrict;
alter table public.class_schedules add column if not exists subject_name varchar(160) not null default 'Scheduled Class';

insert into public.classrooms (name, capacity, target_temperature, ac_status)
select distinct classroom_name, 1, 22, 'Idle'
from public.class_schedules
where classroom_name is not null
on conflict do nothing;

update public.class_schedules as schedule
set classroom_id = classroom.id
from public.classrooms as classroom
where schedule.classroom_id is null
  and lower(schedule.classroom_name) = lower(classroom.name);

update public.class_schedules
set original_teacher_account_id = teacher_account_id
where original_teacher_account_id is null;

create index if not exists ix_class_schedules_teacher_date
on public.class_schedules (teacher_account_id, schedule_date, start_time);
create index if not exists ix_class_schedules_classroom_date
on public.class_schedules (lower(classroom_name), schedule_date, start_time);

-- These constraints are the final authority for the flowchart's
-- "Check schedule conflict?" decision. They stop concurrent requests from
-- giving one teacher or one classroom overlapping classes.
do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'ex_class_schedules_teacher_overlap') then
        alter table public.class_schedules add constraint ex_class_schedules_teacher_overlap
        exclude using gist (
            teacher_account_id with =,
            tsrange(schedule_date + start_time, schedule_date + end_time, '[)') with &&
        );
    end if;

    if not exists (select 1 from pg_constraint where conname = 'ex_class_schedules_classroom_overlap') then
        alter table public.class_schedules add constraint ex_class_schedules_classroom_overlap
        exclude using gist (
            lower(classroom_name) with =,
            tsrange(schedule_date + start_time, schedule_date + end_time, '[)') with &&
        );
    end if;
end;
$$;

create table if not exists public.attendance_logs (
    id bigint generated by default as identity primary key,
    class_schedule_id bigint unique references public.class_schedules(id) on delete set null,
    teacher_account_id bigint not null references public.user_accounts(id) on delete cascade,
    classroom_id bigint not null references public.classrooms(id) on delete restrict,
    time_in_utc timestamptz not null default current_timestamp,
    time_out_utc timestamptz,
    verification_method varchar(40) not null default 'Biometric',
    status varchar(24) not null default 'Active' check (status in ('Active', 'Completed'))
);

create index if not exists ix_attendance_logs_teacher_time
on public.attendance_logs (teacher_account_id, time_in_utc desc);

create table if not exists public.teacher_requests (
    id bigint generated by default as identity primary key,
    teacher_account_id bigint not null references public.user_accounts(id) on delete cascade,
    request_type varchar(16) not null check (request_type in ('Leave', 'EarlyOut', 'Overtime')),
    request_date date not null,
    reason varchar(1000) not null,
    needs_substitute boolean not null default false,
    substitute_teacher_account_id bigint references public.user_accounts(id) on delete set null,
    status varchar(16) not null default 'Pending' check (status in ('Pending', 'Approved', 'Rejected')),
    admin_response varchar(1000),
    reviewed_by_account_id bigint references public.user_accounts(id) on delete set null,
    created_utc timestamptz not null default current_timestamp,
    reviewed_utc timestamptz
);

create index if not exists ix_teacher_requests_status
on public.teacher_requests (status, created_utc desc);

create table if not exists public.support_tickets (
    id bigint generated by default as identity primary key,
    teacher_account_id bigint not null references public.user_accounts(id) on delete cascade,
    category varchar(100) not null,
    details varchar(2000) not null,
    status varchar(16) not null default 'Open' check (status in ('Open', 'Resolved', 'Dismissed')),
    admin_response varchar(2000),
    reviewed_by_account_id bigint references public.user_accounts(id) on delete set null,
    created_utc timestamptz not null default current_timestamp,
    resolved_utc timestamptz
);

create index if not exists ix_support_tickets_status
on public.support_tickets (status, created_utc desc);

create table if not exists public.temperature_logs (
    id bigint generated by default as identity primary key,
    classroom_id bigint not null references public.classrooms(id) on delete cascade,
    actor_account_id bigint references public.user_accounts(id) on delete set null,
    measured_temperature numeric(4,1),
    target_temperature integer check (target_temperature between 16 and 30),
    event_type varchar(32) not null,
    notes varchar(1000),
    recorded_utc timestamptz not null default current_timestamp
);

create index if not exists ix_temperature_logs_classroom_time
on public.temperature_logs (classroom_id, recorded_utc desc);

create or replace function public.smartclass_set_updated_utc()
returns trigger
language plpgsql
as $$
begin
    new.updated_utc = current_timestamp;
    return new;
end;
$$;

drop trigger if exists trg_user_accounts_set_updated_utc on public.user_accounts;
create trigger trg_user_accounts_set_updated_utc before update on public.user_accounts
for each row execute function public.smartclass_set_updated_utc();
drop trigger if exists trg_classrooms_set_updated_utc on public.classrooms;
create trigger trg_classrooms_set_updated_utc before update on public.classrooms
for each row execute function public.smartclass_set_updated_utc();
drop trigger if exists trg_class_schedules_set_updated_utc on public.class_schedules;
create trigger trg_class_schedules_set_updated_utc before update on public.class_schedules
for each row execute function public.smartclass_set_updated_utc();

-- RLS stays on. The Npgsql server connection should use the database owner
-- (`postgres` / the Supabase Connect string), which bypasses RLS. No browser
-- Data API policy is deliberately created for these sensitive account tables.
alter table public.user_accounts enable row level security;
alter table public.classrooms enable row level security;
alter table public.fingerprint_templates enable row level security;
alter table public.password_reset_tokens enable row level security;
alter table public.class_schedules enable row level security;
alter table public.attendance_logs enable row level security;
alter table public.teacher_requests enable row level security;
alter table public.support_tickets enable row level security;
alter table public.temperature_logs enable row level security;

commit;

-- Verification query: it should list the nine SmartClass AC tables.
select tablename
from pg_tables
where schemaname = 'public'
  and tablename in (
      'user_accounts', 'classrooms', 'fingerprint_templates', 'password_reset_tokens',
      'class_schedules', 'attendance_logs', 'teacher_requests', 'support_tickets', 'temperature_logs'
  )
order by tablename;

-- Do not insert `user_accounts` manually: the application creates PBKDF2-SHA256
-- password hashes and ten fingerprint template IDs when an administrator adds a
-- teacher. Use the Admin dashboard for regular teacher/classroom/schedule setup.
