using Npgsql;
using NpgsqlTypes;
using System.Security.Cryptography;
using System.Text;

namespace SmartClassAC.Services;

/// <summary>
/// Server-side persistence for the Supabase PostgreSQL database. Credentials stay on the server;
/// browser clients never receive a Supabase database password.
/// </summary>
public sealed class SupabasePostgresUserAccountRepository : IUserAccountRepository
{
    private const string ConnectionStringName = "SmartClassSupabase";
    private readonly string _connectionString;

    public SupabasePostgresUserAccountRepository(IConfiguration configuration)
    {
        var configuredConnectionString = configuration.GetConnectionString(ConnectionStringName);
        if (string.IsNullOrWhiteSpace(configuredConnectionString))
        {
            throw new InvalidOperationException(
                "Set ConnectionStrings:SmartClassSupabase with the PostgreSQL connection string from Supabase Connect.");
        }

        NpgsqlConnectionStringBuilder builder;
        try
        {
            builder = new NpgsqlConnectionStringBuilder(configuredConnectionString);
        }
        catch (ArgumentException exception)
        {
            throw new InvalidOperationException("The Supabase PostgreSQL connection string is invalid.", exception);
        }

        if (string.IsNullOrWhiteSpace(builder.Host))
        {
            throw new InvalidOperationException("The Supabase PostgreSQL connection string must include its host.");
        }

        if (builder.SslMode is SslMode.Disable or SslMode.Allow or SslMode.Prefer)
        {
            throw new InvalidOperationException(
                "Supabase requires an encrypted connection. Set SSL Mode=Require or, when a root certificate is configured, SSL Mode=VerifyFull.");
        }

        builder.ApplicationName = "SmartClassAC";
        _connectionString = builder.ConnectionString;
    }

    public async Task InitializeAsync(DefaultAdminOptions defaultAdmin, string passwordHash, CancellationToken cancellationToken)
    {
        await using var connection = await OpenConnectionAsync(cancellationToken);

        await ExecuteAsync(connection, @"
            CREATE TABLE IF NOT EXISTS user_accounts (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username VARCHAR(100) NOT NULL,
                display_name VARCHAR(160) NOT NULL,
                email VARCHAR(254),
                phone VARCHAR(40),
                password_hash VARCHAR(512) NOT NULL,
                role VARCHAR(16) NOT NULL CHECK (role IN ('Admin', 'Teacher')),
                is_default_admin BOOLEAN NOT NULL DEFAULT FALSE,
                is_active BOOLEAN NOT NULL DEFAULT TRUE,
                created_utc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_utc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            );", cancellationToken);
        await ExecuteAsync(connection, "ALTER TABLE user_accounts ADD COLUMN IF NOT EXISTS phone VARCHAR(40);", cancellationToken);
        await ExecuteAsync(connection, @"
            CREATE UNIQUE INDEX IF NOT EXISTS uq_user_accounts_username_ci
            ON user_accounts (LOWER(username));
            CREATE UNIQUE INDEX IF NOT EXISTS uq_user_accounts_email_ci
            ON user_accounts (LOWER(email)) WHERE email IS NOT NULL;
            CREATE UNIQUE INDEX IF NOT EXISTS uq_user_accounts_default_admin
            ON user_accounts (is_default_admin) WHERE is_default_admin;", cancellationToken);

        await ExecuteAsync(connection, @"
            CREATE TABLE IF NOT EXISTS classrooms (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(100) NOT NULL,
                capacity INTEGER NOT NULL CHECK (capacity BETWEEN 1 AND 1000),
                target_temperature INTEGER NOT NULL DEFAULT 22 CHECK (target_temperature BETWEEN 16 AND 30),
                current_temperature NUMERIC(4,1),
                ac_status VARCHAR(24) NOT NULL DEFAULT 'Idle',
                is_active BOOLEAN NOT NULL DEFAULT TRUE,
                created_utc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_utc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
            CREATE UNIQUE INDEX IF NOT EXISTS uq_classrooms_name_ci ON classrooms (LOWER(name));", cancellationToken);

        await ExecuteAsync(connection, @"
            CREATE TABLE IF NOT EXISTS fingerprint_templates (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_account_id BIGINT NOT NULL REFERENCES user_accounts(id) ON DELETE CASCADE,
                finger_position VARCHAR(32) NOT NULL,
                template_identifier UUID NOT NULL,
                created_utc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT uq_fingerprint_templates_identifier UNIQUE (template_identifier),
                CONSTRAINT uq_fingerprint_templates_user_finger UNIQUE (user_account_id, finger_position)
            );
            CREATE TABLE IF NOT EXISTS password_reset_tokens (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_account_id BIGINT NOT NULL REFERENCES user_accounts(id) ON DELETE CASCADE,
                token_hash CHAR(64) NOT NULL UNIQUE,
                expires_utc TIMESTAMPTZ NOT NULL,
                used_utc TIMESTAMPTZ,
                created_utc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
            CREATE INDEX IF NOT EXISTS ix_password_reset_tokens_account_expiry
            ON password_reset_tokens (user_account_id, expires_utc DESC);", cancellationToken);

        await ExecuteAsync(connection, @"
            CREATE TABLE IF NOT EXISTS class_schedules (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                teacher_account_id BIGINT NOT NULL REFERENCES user_accounts(id) ON DELETE CASCADE,
                original_teacher_account_id BIGINT REFERENCES user_accounts(id) ON DELETE CASCADE,
                classroom_id BIGINT REFERENCES classrooms(id) ON DELETE RESTRICT,
                classroom_name VARCHAR(100) NOT NULL,
                subject_name VARCHAR(160) NOT NULL DEFAULT 'Scheduled Class',
                schedule_date DATE NOT NULL,
                start_time TIME NOT NULL,
                end_time TIME NOT NULL,
                created_utc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_utc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT ck_class_schedules_time_range CHECK (end_time > start_time)
            );
            ALTER TABLE class_schedules ADD COLUMN IF NOT EXISTS original_teacher_account_id BIGINT REFERENCES user_accounts(id) ON DELETE CASCADE;
            ALTER TABLE class_schedules ADD COLUMN IF NOT EXISTS classroom_id BIGINT REFERENCES classrooms(id) ON DELETE RESTRICT;
            ALTER TABLE class_schedules ADD COLUMN IF NOT EXISTS subject_name VARCHAR(160) NOT NULL DEFAULT 'Scheduled Class';", cancellationToken);

        await ExecuteAsync(connection, @"
            INSERT INTO classrooms (name, capacity, target_temperature, ac_status)
            SELECT DISTINCT classroom_name, 1, 22, 'Idle'
            FROM class_schedules
            WHERE classroom_name IS NOT NULL
            ON CONFLICT DO NOTHING;

            UPDATE class_schedules AS schedule
            SET classroom_id = classroom.id
            FROM classrooms AS classroom
            WHERE schedule.classroom_id IS NULL
              AND LOWER(schedule.classroom_name) = LOWER(classroom.name);

            UPDATE class_schedules
            SET original_teacher_account_id = teacher_account_id
            WHERE original_teacher_account_id IS NULL;", cancellationToken);

        await ExecuteAsync(connection, @"
            CREATE INDEX IF NOT EXISTS ix_class_schedules_teacher_date
            ON class_schedules (teacher_account_id, schedule_date, start_time);
            CREATE INDEX IF NOT EXISTS ix_class_schedules_classroom_date
            ON class_schedules (LOWER(classroom_name), schedule_date, start_time);", cancellationToken);

        await ExecuteAsync(connection, @"
            CREATE EXTENSION IF NOT EXISTS btree_gist;
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ex_class_schedules_teacher_overlap') THEN
                    ALTER TABLE class_schedules ADD CONSTRAINT ex_class_schedules_teacher_overlap
                    EXCLUDE USING gist (
                        teacher_account_id WITH =,
                        tsrange(schedule_date + start_time, schedule_date + end_time, '[)') WITH &&
                    );
                END IF;
                IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ex_class_schedules_classroom_overlap') THEN
                    ALTER TABLE class_schedules ADD CONSTRAINT ex_class_schedules_classroom_overlap
                    EXCLUDE USING gist (
                        LOWER(classroom_name) WITH =,
                        tsrange(schedule_date + start_time, schedule_date + end_time, '[)') WITH &&
                    );
                END IF;
            END;
            $$;", cancellationToken);

        await ExecuteAsync(connection, @"
            CREATE TABLE IF NOT EXISTS attendance_logs (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                class_schedule_id BIGINT UNIQUE REFERENCES class_schedules(id) ON DELETE SET NULL,
                teacher_account_id BIGINT NOT NULL REFERENCES user_accounts(id) ON DELETE CASCADE,
                classroom_id BIGINT NOT NULL REFERENCES classrooms(id) ON DELETE RESTRICT,
                time_in_utc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                time_out_utc TIMESTAMPTZ,
                verification_method VARCHAR(40) NOT NULL DEFAULT 'Biometric',
                status VARCHAR(24) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Completed'))
            );
            CREATE INDEX IF NOT EXISTS ix_attendance_logs_teacher_time ON attendance_logs (teacher_account_id, time_in_utc DESC);
            CREATE UNIQUE INDEX IF NOT EXISTS uq_attendance_logs_one_active_teacher
            ON attendance_logs (teacher_account_id) WHERE time_out_utc IS NULL;

            CREATE TABLE IF NOT EXISTS teacher_requests (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                teacher_account_id BIGINT NOT NULL REFERENCES user_accounts(id) ON DELETE CASCADE,
                request_type VARCHAR(16) NOT NULL CHECK (request_type IN ('Leave', 'EarlyOut', 'Overtime')),
                request_date DATE NOT NULL,
                reason VARCHAR(1000) NOT NULL,
                needs_substitute BOOLEAN NOT NULL DEFAULT FALSE,
                substitute_teacher_account_id BIGINT REFERENCES user_accounts(id) ON DELETE SET NULL,
                status VARCHAR(16) NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Approved', 'Rejected')),
                admin_response VARCHAR(1000),
                reviewed_by_account_id BIGINT REFERENCES user_accounts(id) ON DELETE SET NULL,
                created_utc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                reviewed_utc TIMESTAMPTZ
            );
            CREATE INDEX IF NOT EXISTS ix_teacher_requests_status ON teacher_requests (status, created_utc DESC);
            CREATE UNIQUE INDEX IF NOT EXISTS uq_teacher_requests_pending_day
            ON teacher_requests (teacher_account_id, request_type, request_date)
            WHERE status = 'Pending';

            CREATE TABLE IF NOT EXISTS support_tickets (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                teacher_account_id BIGINT NOT NULL REFERENCES user_accounts(id) ON DELETE CASCADE,
                category VARCHAR(100) NOT NULL,
                details VARCHAR(2000) NOT NULL,
                status VARCHAR(16) NOT NULL DEFAULT 'Open' CHECK (status IN ('Open', 'Resolved', 'Dismissed')),
                admin_response VARCHAR(2000),
                reviewed_by_account_id BIGINT REFERENCES user_accounts(id) ON DELETE SET NULL,
                created_utc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                resolved_utc TIMESTAMPTZ
            );
            CREATE INDEX IF NOT EXISTS ix_support_tickets_status ON support_tickets (status, created_utc DESC);

            CREATE TABLE IF NOT EXISTS temperature_logs (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                classroom_id BIGINT NOT NULL REFERENCES classrooms(id) ON DELETE CASCADE,
                actor_account_id BIGINT REFERENCES user_accounts(id) ON DELETE SET NULL,
                measured_temperature NUMERIC(4,1),
                target_temperature INTEGER CHECK (target_temperature BETWEEN 16 AND 30),
                event_type VARCHAR(32) NOT NULL,
                notes VARCHAR(1000),
                recorded_utc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
            CREATE INDEX IF NOT EXISTS ix_temperature_logs_classroom_time ON temperature_logs (classroom_id, recorded_utc DESC);", cancellationToken);

        await ExecuteAsync(connection, @"
            CREATE OR REPLACE FUNCTION public.smartclass_set_updated_utc()
            RETURNS TRIGGER LANGUAGE plpgsql AS $$
            BEGIN
                NEW.updated_utc = CURRENT_TIMESTAMP;
                RETURN NEW;
            END;
            $$;
            DROP TRIGGER IF EXISTS trg_user_accounts_set_updated_utc ON user_accounts;
            CREATE TRIGGER trg_user_accounts_set_updated_utc BEFORE UPDATE ON user_accounts
            FOR EACH ROW EXECUTE FUNCTION public.smartclass_set_updated_utc();
            DROP TRIGGER IF EXISTS trg_classrooms_set_updated_utc ON classrooms;
            CREATE TRIGGER trg_classrooms_set_updated_utc BEFORE UPDATE ON classrooms
            FOR EACH ROW EXECUTE FUNCTION public.smartclass_set_updated_utc();
            DROP TRIGGER IF EXISTS trg_class_schedules_set_updated_utc ON class_schedules;
            CREATE TRIGGER trg_class_schedules_set_updated_utc BEFORE UPDATE ON class_schedules
            FOR EACH ROW EXECUTE FUNCTION public.smartclass_set_updated_utc();", cancellationToken);

        await ExecuteAsync(connection, @"
            ALTER TABLE user_accounts ENABLE ROW LEVEL SECURITY;
            ALTER TABLE classrooms ENABLE ROW LEVEL SECURITY;
            ALTER TABLE fingerprint_templates ENABLE ROW LEVEL SECURITY;
            ALTER TABLE password_reset_tokens ENABLE ROW LEVEL SECURITY;
            ALTER TABLE class_schedules ENABLE ROW LEVEL SECURITY;
            ALTER TABLE attendance_logs ENABLE ROW LEVEL SECURITY;
            ALTER TABLE teacher_requests ENABLE ROW LEVEL SECURITY;
            ALTER TABLE support_tickets ENABLE ROW LEVEL SECURITY;
            ALTER TABLE temperature_logs ENABLE ROW LEVEL SECURITY;", cancellationToken);

        await SeedDefaultAdminAsync(connection, defaultAdmin, passwordHash, cancellationToken);
    }

    public async Task CheckHealthAsync(CancellationToken cancellationToken = default)
    {
        await using var connection = await OpenConnectionAsync(cancellationToken);
        await using var command = connection.CreateCommand();
        command.CommandText = "SELECT 1;";
        await command.ExecuteScalarAsync(cancellationToken);
    }

    public async Task<UserAccountRecord?> FindByIdentifierAsync(string usernameOrEmail, CancellationToken cancellationToken = default)
    {
        await using var connection = await OpenConnectionAsync(cancellationToken);
        await using var command = connection.CreateCommand();
        command.CommandText = @"
            SELECT id, username, display_name, email, password_hash, role, is_default_admin
            FROM user_accounts
            WHERE (LOWER(username) = LOWER(@identifier) OR LOWER(email) = LOWER(@identifier))
              AND is_active = TRUE
            LIMIT 1;";
        command.Parameters.AddWithValue("@identifier", NpgsqlDbType.Varchar, usernameOrEmail);
        await using var reader = await command.ExecuteReaderAsync(cancellationToken);
        return await reader.ReadAsync(cancellationToken)
            ? new UserAccountRecord(reader.GetInt64(0), reader.GetString(1), reader.GetString(2), reader.IsDBNull(3) ? null : reader.GetString(3), reader.GetString(4), Enum.Parse<UserRole>(reader.GetString(5)), reader.GetBoolean(6))
            : null;
    }

    public async Task<UserAccountRecord?> FindByIdAsync(long accountId, CancellationToken cancellationToken = default)
    {
        await using var connection = await OpenConnectionAsync(cancellationToken);
        await using var command = connection.CreateCommand();
        command.CommandText = @"
            SELECT id, username, display_name, email, password_hash, role, is_default_admin
            FROM user_accounts
            WHERE id = @id AND is_active = TRUE;";
        command.Parameters.AddWithValue("@id", NpgsqlDbType.Bigint, accountId);
        await using var reader = await command.ExecuteReaderAsync(cancellationToken);
        return await reader.ReadAsync(cancellationToken)
            ? new UserAccountRecord(reader.GetInt64(0), reader.GetString(1), reader.GetString(2), reader.IsDBNull(3) ? null : reader.GetString(3), reader.GetString(4), Enum.Parse<UserRole>(reader.GetString(5)), reader.GetBoolean(6))
            : null;
    }

    public async Task<bool> IsInitialAdminSetupRequiredAsync(CancellationToken cancellationToken = default)
    {
        await using var connection = await OpenConnectionAsync(cancellationToken);
        await using var command = connection.CreateCommand();
        command.CommandText = "SELECT EXISTS(SELECT 1 FROM user_accounts WHERE is_default_admin = TRUE AND email IS NULL);";
        return (bool)(await command.ExecuteScalarAsync(cancellationToken) ?? false);
    }

    public async Task<bool> SetInitialAdminEmailAsync(string email, CancellationToken cancellationToken = default)
    {
        await using var connection = await OpenConnectionAsync(cancellationToken);
        await using var command = connection.CreateCommand();
        command.CommandText = "UPDATE user_accounts SET email = @email WHERE is_default_admin = TRUE AND email IS NULL;";
        command.Parameters.AddWithValue("@email", NpgsqlDbType.Varchar, email);
        try
        {
            return await command.ExecuteNonQueryAsync(cancellationToken) == 1;
        }
        catch (PostgresException exception) when (exception.SqlState == PostgresErrorCodes.UniqueViolation)
        {
            return false;
        }
    }

    public async Task<OperationResult> UpdateDefaultAdminCredentialsAsync(long accountId, string email, string? passwordHash, CancellationToken cancellationToken = default)
    {
        await using var connection = await OpenConnectionAsync(cancellationToken);
        await using var command = connection.CreateCommand();
        command.CommandText = passwordHash is null
            ? "UPDATE user_accounts SET email = @email WHERE id = @id AND is_default_admin = TRUE;"
            : "UPDATE user_accounts SET email = @email, password_hash = @passwordHash WHERE id = @id AND is_default_admin = TRUE;";
        command.Parameters.AddWithValue("@id", NpgsqlDbType.Bigint, accountId);
        command.Parameters.AddWithValue("@email", NpgsqlDbType.Varchar, email);
        if (passwordHash is not null) command.Parameters.AddWithValue("@passwordHash", NpgsqlDbType.Varchar, passwordHash);
        try
        {
            return await command.ExecuteNonQueryAsync(cancellationToken) == 1
                ? OperationResult.Success()
                : OperationResult.Failure("The default administrator account was not found.");
        }
        catch (PostgresException exception) when (exception.SqlState == PostgresErrorCodes.UniqueViolation)
        {
            return OperationResult.Failure("That email is already registered to another account.");
        }
    }

    public async Task<OperationResult> CreateTeacherAsync(CreateTeacherRequest request, string passwordHash, CancellationToken cancellationToken = default)
    {
        await using var connection = await OpenConnectionAsync(cancellationToken);
        await using var transaction = await connection.BeginTransactionAsync(cancellationToken);
        try
        {
            await using var account = connection.CreateCommand();
            account.Transaction = transaction;
            account.CommandText = @"
                INSERT INTO user_accounts (username, display_name, email, password_hash, role)
                VALUES (@username, @displayName, @email, @passwordHash, 'Teacher')
                RETURNING id;";
            account.Parameters.AddWithValue("@username", NpgsqlDbType.Varchar, request.Username);
            account.Parameters.AddWithValue("@displayName", NpgsqlDbType.Varchar, request.DisplayName);
            account.Parameters.AddWithValue("@email", NpgsqlDbType.Varchar, request.Email);
            account.Parameters.AddWithValue("@passwordHash", NpgsqlDbType.Varchar, passwordHash);
            var teacherId = (long)(await account.ExecuteScalarAsync(cancellationToken)
                ?? throw new InvalidOperationException("Supabase did not return the new teacher ID."));

            await using var templates = connection.CreateCommand();
            templates.Transaction = transaction;
            var values = new List<string>(FingerPositions.Length);
            templates.Parameters.AddWithValue("@teacherId", NpgsqlDbType.Bigint, teacherId);
            for (var index = 0; index < FingerPositions.Length; index++)
            {
                var finger = $"@finger{index}";
                var template = $"@template{index}";
                values.Add($"(@teacherId, {finger}, {template})");
                templates.Parameters.AddWithValue(finger, NpgsqlDbType.Varchar, FingerPositions[index]);
                templates.Parameters.AddWithValue(template, NpgsqlDbType.Uuid, Guid.NewGuid());
            }
            templates.CommandText = $"INSERT INTO fingerprint_templates (user_account_id, finger_position, template_identifier) VALUES {string.Join(", ", values)};";
            if (await templates.ExecuteNonQueryAsync(cancellationToken) != FingerPositions.Length)
            {
                throw new InvalidOperationException("All fingerprint templates could not be saved for the teacher account.");
            }

            await transaction.CommitAsync(cancellationToken);
            return OperationResult.Success();
        }
        catch (PostgresException exception) when (exception.SqlState == PostgresErrorCodes.UniqueViolation)
        {
            await transaction.RollbackAsync(cancellationToken);
            return OperationResult.Failure("That username or email is already registered.");
        }
        catch
        {
            await transaction.RollbackAsync(cancellationToken);
            throw;
        }
    }

    public async Task<IReadOnlyList<TeacherDirectoryEntry>> GetTeachersAsync(CancellationToken cancellationToken = default)
    {
        var items = new List<TeacherDirectoryEntry>();
        await using var connection = await OpenConnectionAsync(cancellationToken);
        await using var command = connection.CreateCommand();
        command.CommandText = @"
            SELECT u.id, u.display_name, u.username, u.email, COUNT(f.id)
            FROM user_accounts u LEFT JOIN fingerprint_templates f ON f.user_account_id = u.id
            WHERE u.role = 'Teacher' AND u.is_active = TRUE
            GROUP BY u.id, u.display_name, u.username, u.email ORDER BY u.display_name;";
        await using var reader = await command.ExecuteReaderAsync(cancellationToken);
        while (await reader.ReadAsync(cancellationToken))
        {
            items.Add(new TeacherDirectoryEntry(reader.GetInt64(0), reader.GetString(1), reader.GetString(2), reader.GetString(3), reader.GetInt32(4)));
        }
        return items;
    }

    public async Task<OperationResult> DeleteTeacherAsync(long accountId, CancellationToken cancellationToken = default)
    {
        await using var connection = await OpenConnectionAsync(cancellationToken);

        await using (var scheduled = connection.CreateCommand())
        {
            scheduled.CommandText = @"
                SELECT EXISTS(
                    SELECT 1 FROM class_schedules
                    WHERE teacher_account_id = @id AND schedule_date >= CURRENT_DATE
                );";
            scheduled.Parameters.AddWithValue("@id", NpgsqlDbType.Bigint, accountId);
            if ((bool)(await scheduled.ExecuteScalarAsync(cancellationToken) ?? false))
            {
                return OperationResult.Failure("Delete or reassign this teacher's current and future schedules before removing the account.");
            }
        }

        await using var command = connection.CreateCommand();
        command.CommandText = @"
            DELETE FROM user_accounts
            WHERE id = @id AND role = 'Teacher';";
        command.Parameters.AddWithValue("@id", NpgsqlDbType.Bigint, accountId);
        return await command.ExecuteNonQueryAsync(cancellationToken) == 1
            ? OperationResult.Success()
            : OperationResult.Failure("The teacher account was not found.");
    }

    public async Task<IReadOnlyList<ClassroomEntry>> GetClassroomsAsync(CancellationToken cancellationToken = default)
    {
        var items = new List<ClassroomEntry>();
        await using var connection = await OpenConnectionAsync(cancellationToken);
        await using var command = connection.CreateCommand();
        command.CommandText = @"
            SELECT id, name, capacity, target_temperature, current_temperature, ac_status, is_active
            FROM classrooms WHERE is_active = TRUE ORDER BY name;";
        await using var reader = await command.ExecuteReaderAsync(cancellationToken);
        while (await reader.ReadAsync(cancellationToken))
        {
            items.Add(new ClassroomEntry(reader.GetInt64(0), reader.GetString(1), reader.GetInt32(2), reader.GetInt32(3), reader.IsDBNull(4) ? null : reader.GetDecimal(4), reader.GetString(5), reader.GetBoolean(6)));
        }
        return items;
    }

    public async Task<OperationResult> CreateClassroomAsync(CreateClassroomRequest request, CancellationToken cancellationToken = default)
    {
        await using var connection = await OpenConnectionAsync(cancellationToken);
        await using var command = connection.CreateCommand();
        command.CommandText = @"
            INSERT INTO classrooms (name, capacity, target_temperature, current_temperature, ac_status)
            VALUES (@name, @capacity, @targetTemperature, @targetTemperature, 'Idle');";
        AddClassroomParameters(command, request.Name, request.Capacity, request.TargetTemperature);
        try
        {
            await command.ExecuteNonQueryAsync(cancellationToken);
            return OperationResult.Success();
        }
        catch (PostgresException exception) when (exception.SqlState == PostgresErrorCodes.UniqueViolation)
        {
            return OperationResult.Failure("A classroom with that name already exists.");
        }
    }

    public async Task<OperationResult> UpdateClassroomAsync(UpdateClassroomRequest request, CancellationToken cancellationToken = default)
    {
        await using var connection = await OpenConnectionAsync(cancellationToken);
        await using var command = connection.CreateCommand();
        command.CommandText = @"
            UPDATE classrooms
            SET name = @name, capacity = @capacity, target_temperature = @targetTemperature, is_active = @isActive
            WHERE id = @id;";
        command.Parameters.AddWithValue("@id", NpgsqlDbType.Bigint, request.Id);
        AddClassroomParameters(command, request.Name, request.Capacity, request.TargetTemperature);
        command.Parameters.AddWithValue("@isActive", NpgsqlDbType.Boolean, request.IsActive);
        try
        {
            return await command.ExecuteNonQueryAsync(cancellationToken) == 1
                ? OperationResult.Success()
                : OperationResult.Failure("The classroom was not found.");
        }
        catch (PostgresException exception) when (exception.SqlState == PostgresErrorCodes.UniqueViolation)
        {
            return OperationResult.Failure("A classroom with that name already exists.");
        }
    }

    public async Task<OperationResult> DeleteClassroomAsync(long classroomId, CancellationToken cancellationToken = default)
    {
        await using var connection = await OpenConnectionAsync(cancellationToken);

        await using (var scheduled = connection.CreateCommand())
        {
            scheduled.CommandText = @"
                SELECT EXISTS(
                    SELECT 1 FROM class_schedules
                    WHERE classroom_id = @id AND schedule_date >= CURRENT_DATE
                );";
            scheduled.Parameters.AddWithValue("@id", NpgsqlDbType.Bigint, classroomId);
            if ((bool)(await scheduled.ExecuteScalarAsync(cancellationToken) ?? false))
            {
                return OperationResult.Failure("Delete or move this classroom's current and future schedules before removing the room.");
            }
        }

        await using var command = connection.CreateCommand();
        command.CommandText = @"
            UPDATE classrooms
            SET is_active = FALSE, ac_status = 'Retired'
            WHERE id = @id AND is_active = TRUE;";
        command.Parameters.AddWithValue("@id", NpgsqlDbType.Bigint, classroomId);
        return await command.ExecuteNonQueryAsync(cancellationToken) == 1
            ? OperationResult.Success()
            : OperationResult.Failure("The active classroom was not found.");
    }

    public async Task<OperationResult> CreateScheduleAsync(CreateScheduleRequest request, CancellationToken cancellationToken = default)
    {
        await using var connection = await OpenConnectionAsync(cancellationToken);
        await using var transaction = await connection.BeginTransactionAsync(cancellationToken);
        try
        {
            await using var conflict = connection.CreateCommand();
            conflict.Transaction = transaction;
            conflict.CommandText = @"
                SELECT EXISTS(
                    SELECT 1 FROM class_schedules
                    WHERE schedule_date = @date
                      AND (teacher_account_id = @teacherId OR classroom_id = @classroomId)
                      AND start_time < @endTime AND end_time > @startTime
                );";
            AddScheduleParameters(conflict, request);
            if ((bool)(await conflict.ExecuteScalarAsync(cancellationToken) ?? false))
            {
                await transaction.RollbackAsync(cancellationToken);
                return OperationResult.Failure("The selected teacher or classroom already has an overlapping schedule.");
            }

            await using var create = connection.CreateCommand();
            create.Transaction = transaction;
            create.CommandText = @"
                INSERT INTO class_schedules (
                    teacher_account_id, original_teacher_account_id, classroom_id, classroom_name,
                    subject_name, schedule_date, start_time, end_time)
                SELECT teacher.id, teacher.id, classroom.id, classroom.name,
                       @subject, @date, @startTime, @endTime
                FROM user_accounts teacher CROSS JOIN classrooms classroom
                WHERE teacher.id = @teacherId AND teacher.role = 'Teacher' AND teacher.is_active = TRUE
                  AND classroom.id = @classroomId AND classroom.is_active = TRUE;";
            AddScheduleParameters(create, request);
            if (await create.ExecuteNonQueryAsync(cancellationToken) != 1)
            {
                await transaction.RollbackAsync(cancellationToken);
                return OperationResult.Failure("The selected teacher or classroom is no longer available.");
            }

            await transaction.CommitAsync(cancellationToken);
            return OperationResult.Success();
        }
        catch (PostgresException exception) when (exception.SqlState == PostgresErrorCodes.ExclusionViolation)
        {
            await transaction.RollbackAsync(cancellationToken);
            return OperationResult.Failure("The selected teacher or classroom already has an overlapping schedule.");
        }
        catch
        {
            await transaction.RollbackAsync(cancellationToken);
            throw;
        }
    }

    public Task<IReadOnlyList<ScheduleDirectoryEntry>> GetSchedulesAsync(CancellationToken cancellationToken = default) =>
        ReadSchedulesAsync(null, cancellationToken);

    public Task<IReadOnlyList<ScheduleDirectoryEntry>> GetTeacherSchedulesAsync(long accountId, CancellationToken cancellationToken = default) =>
        ReadSchedulesAsync(accountId, cancellationToken);

    public async Task<OperationResult> DeleteScheduleAsync(long scheduleId, CancellationToken cancellationToken = default)
    {
        await using var connection = await OpenConnectionAsync(cancellationToken);
        await using var command = connection.CreateCommand();
        command.CommandText = "DELETE FROM class_schedules WHERE id = @id;";
        command.Parameters.AddWithValue("@id", NpgsqlDbType.Bigint, scheduleId);
        return await command.ExecuteNonQueryAsync(cancellationToken) == 1
            ? OperationResult.Success()
            : OperationResult.Failure("The schedule was not found.");
    }

    public async Task<PasswordResetDelivery?> CreatePasswordResetAsync(string email, DateTimeOffset expiresUtc, CancellationToken cancellationToken = default)
    {
        await using var connection = await OpenConnectionAsync(cancellationToken);
        await using var transaction = await connection.BeginTransactionAsync(cancellationToken);
        try
        {
            long accountId;
            string recipient;
            await using (var find = connection.CreateCommand())
            {
                find.Transaction = transaction;
                find.CommandText = @"
                    SELECT id, email
                    FROM user_accounts
                    WHERE LOWER(email) = LOWER(@email) AND is_active = TRUE
                    LIMIT 1
                    FOR UPDATE;";
                find.Parameters.AddWithValue("@email", NpgsqlDbType.Varchar, email);
                await using var reader = await find.ExecuteReaderAsync(cancellationToken);
                if (!await reader.ReadAsync(cancellationToken))
                {
                    await transaction.RollbackAsync(cancellationToken);
                    return null;
                }

                accountId = reader.GetInt64(0);
                recipient = reader.GetString(1);
            }

            var rawToken = CreateSecureToken();
            var tokenHash = HashResetToken(rawToken);

            await using (var expireOld = connection.CreateCommand())
            {
                expireOld.Transaction = transaction;
                expireOld.CommandText = @"
                    UPDATE password_reset_tokens
                    SET used_utc = CURRENT_TIMESTAMP
                    WHERE user_account_id = @accountId AND used_utc IS NULL;";
                expireOld.Parameters.AddWithValue("@accountId", NpgsqlDbType.Bigint, accountId);
                await expireOld.ExecuteNonQueryAsync(cancellationToken);
            }

            await using (var insert = connection.CreateCommand())
            {
                insert.Transaction = transaction;
                insert.CommandText = @"
                    INSERT INTO password_reset_tokens (user_account_id, token_hash, expires_utc)
                    VALUES (@accountId, @tokenHash, @expiresUtc);";
                insert.Parameters.AddWithValue("@accountId", NpgsqlDbType.Bigint, accountId);
                insert.Parameters.AddWithValue("@tokenHash", NpgsqlDbType.Char, tokenHash);
                insert.Parameters.AddWithValue("@expiresUtc", NpgsqlDbType.TimestampTz, expiresUtc);
                await insert.ExecuteNonQueryAsync(cancellationToken);
            }

            await transaction.CommitAsync(cancellationToken);
            return new PasswordResetDelivery(recipient, rawToken);
        }
        catch
        {
            await transaction.RollbackAsync(cancellationToken);
            throw;
        }
    }

    public async Task<bool> ResetPasswordAsync(string rawToken, string passwordHash, CancellationToken cancellationToken = default)
    {
        var tokenHash = HashResetToken(rawToken);
        await using var connection = await OpenConnectionAsync(cancellationToken);
        await using var transaction = await connection.BeginTransactionAsync(cancellationToken);
        try
        {
            long accountId;
            await using (var find = connection.CreateCommand())
            {
                find.Transaction = transaction;
                find.CommandText = @"
                    SELECT user_account_id
                    FROM password_reset_tokens
                    WHERE token_hash = @tokenHash
                      AND used_utc IS NULL
                      AND expires_utc >= CURRENT_TIMESTAMP
                    LIMIT 1
                    FOR UPDATE;";
                find.Parameters.AddWithValue("@tokenHash", NpgsqlDbType.Char, tokenHash);
                var account = await find.ExecuteScalarAsync(cancellationToken);
                if (account is null)
                {
                    await transaction.RollbackAsync(cancellationToken);
                    return false;
                }

                accountId = (long)account;
            }

            await using (var updateAccount = connection.CreateCommand())
            {
                updateAccount.Transaction = transaction;
                updateAccount.CommandText = @"
                    UPDATE user_accounts
                    SET password_hash = @passwordHash
                    WHERE id = @accountId AND is_active = TRUE;";
                updateAccount.Parameters.AddWithValue("@passwordHash", NpgsqlDbType.Varchar, passwordHash);
                updateAccount.Parameters.AddWithValue("@accountId", NpgsqlDbType.Bigint, accountId);
                if (await updateAccount.ExecuteNonQueryAsync(cancellationToken) != 1)
                {
                    await transaction.RollbackAsync(cancellationToken);
                    return false;
                }
            }

            await using (var useTokens = connection.CreateCommand())
            {
                useTokens.Transaction = transaction;
                useTokens.CommandText = @"
                    UPDATE password_reset_tokens
                    SET used_utc = CURRENT_TIMESTAMP
                    WHERE user_account_id = @accountId AND used_utc IS NULL;";
                useTokens.Parameters.AddWithValue("@accountId", NpgsqlDbType.Bigint, accountId);
                await useTokens.ExecuteNonQueryAsync(cancellationToken);
            }

            await transaction.CommitAsync(cancellationToken);
            return true;
        }
        catch
        {
            await transaction.RollbackAsync(cancellationToken);
            throw;
        }
    }

    public async Task<TeacherProfileEntry?> GetTeacherProfileAsync(long accountId, CancellationToken cancellationToken = default)
    {
        await using var connection = await OpenConnectionAsync(cancellationToken);
        await using var command = connection.CreateCommand();
        command.CommandText = @"
            SELECT u.id, u.display_name, u.username, u.email, u.phone, COUNT(f.id)
            FROM user_accounts u LEFT JOIN fingerprint_templates f ON f.user_account_id = u.id
            WHERE u.id = @id AND u.role = 'Teacher' AND u.is_active = TRUE
            GROUP BY u.id, u.display_name, u.username, u.email, u.phone;";
        command.Parameters.AddWithValue("@id", NpgsqlDbType.Bigint, accountId);
        await using var reader = await command.ExecuteReaderAsync(cancellationToken);
        return await reader.ReadAsync(cancellationToken)
            ? new TeacherProfileEntry(reader.GetInt64(0), reader.GetString(1), reader.GetString(2), reader.GetString(3), reader.IsDBNull(4) ? null : reader.GetString(4), reader.GetInt32(5))
            : null;
    }

    public async Task<OperationResult> UpdateTeacherProfileAsync(long accountId, UpdateTeacherProfileRequest request, string? passwordHash, CancellationToken cancellationToken = default)
    {
        await using var connection = await OpenConnectionAsync(cancellationToken);
        await using var command = connection.CreateCommand();
        command.CommandText = passwordHash is null
            ? "UPDATE user_accounts SET display_name = @name, email = @email, phone = @phone WHERE id = @id AND role = 'Teacher' AND is_active = TRUE;"
            : "UPDATE user_accounts SET display_name = @name, email = @email, phone = @phone, password_hash = @passwordHash WHERE id = @id AND role = 'Teacher' AND is_active = TRUE;";
        command.Parameters.AddWithValue("@id", NpgsqlDbType.Bigint, accountId);
        command.Parameters.AddWithValue("@name", NpgsqlDbType.Varchar, request.DisplayName);
        command.Parameters.AddWithValue("@email", NpgsqlDbType.Varchar, request.Email);
        command.Parameters.AddWithValue("@phone", NpgsqlDbType.Varchar, (object?)request.Phone ?? DBNull.Value);
        if (passwordHash is not null) command.Parameters.AddWithValue("@passwordHash", NpgsqlDbType.Varchar, passwordHash);
        try
        {
            return await command.ExecuteNonQueryAsync(cancellationToken) == 1 ? OperationResult.Success() : OperationResult.Failure("Your teacher account was not found.");
        }
        catch (PostgresException exception) when (exception.SqlState == PostgresErrorCodes.UniqueViolation)
        {
            return OperationResult.Failure("That email is already registered to another account.");
        }
    }

    public async Task<IReadOnlyList<AttendanceLogEntry>> GetAttendanceLogsAsync(long? teacherAccountId = null, CancellationToken cancellationToken = default)
    {
        var items = new List<AttendanceLogEntry>();
        await using var connection = await OpenConnectionAsync(cancellationToken);
        await using var command = connection.CreateCommand();
        command.CommandText = @"
            SELECT a.id, a.teacher_account_id, teacher.display_name, a.classroom_id, classroom.name,
                   a.time_in_utc, a.time_out_utc, a.verification_method, a.status
            FROM attendance_logs a
            INNER JOIN user_accounts teacher ON teacher.id = a.teacher_account_id
            INNER JOIN classrooms classroom ON classroom.id = a.classroom_id
            WHERE (@teacherId IS NULL OR a.teacher_account_id = @teacherId)
            ORDER BY a.time_in_utc DESC;";
        command.Parameters.AddWithValue("@teacherId", NpgsqlDbType.Bigint, (object?)teacherAccountId ?? DBNull.Value);
        await using var reader = await command.ExecuteReaderAsync(cancellationToken);
        while (await reader.ReadAsync(cancellationToken))
        {
            items.Add(new AttendanceLogEntry(reader.GetInt64(0), reader.GetInt64(1), reader.GetString(2), reader.GetInt64(3), reader.GetString(4), reader.GetFieldValue<DateTimeOffset>(5), reader.IsDBNull(6) ? null : reader.GetFieldValue<DateTimeOffset>(6), reader.GetString(7), reader.GetString(8)));
        }
        return items;
    }

    public async Task<OperationResult> StartClassAsync(long teacherAccountId, long scheduleId, DateOnly schoolDate, TimeOnly schoolTime, CancellationToken cancellationToken = default)
    {
        await using var connection = await OpenConnectionAsync(cancellationToken);
        await using var transaction = await connection.BeginTransactionAsync(cancellationToken);
        try
        {
            await using var start = connection.CreateCommand();
            start.Transaction = transaction;
            start.CommandText = @"
                INSERT INTO attendance_logs (class_schedule_id, teacher_account_id, classroom_id, verification_method)
                SELECT schedule.id, schedule.teacher_account_id, schedule.classroom_id, 'Biometric / dashboard verification'
                FROM class_schedules schedule
                WHERE schedule.id = @scheduleId AND schedule.teacher_account_id = @teacherId
                                    AND schedule.schedule_date = @schoolDate
                                    AND @schoolTime >= schedule.start_time
                                    AND @schoolTime < schedule.end_time
                                    AND NOT EXISTS (
                                            SELECT 1
                                            FROM attendance_logs active
                                            WHERE active.teacher_account_id = @teacherId
                                                AND active.time_out_utc IS NULL
                                    )
                ON CONFLICT (class_schedule_id) DO NOTHING
                RETURNING classroom_id;";
            start.Parameters.AddWithValue("@scheduleId", NpgsqlDbType.Bigint, scheduleId);
            start.Parameters.AddWithValue("@teacherId", NpgsqlDbType.Bigint, teacherAccountId);
            start.Parameters.AddWithValue("@schoolDate", NpgsqlDbType.Date, schoolDate);
            start.Parameters.AddWithValue("@schoolTime", NpgsqlDbType.Time, schoolTime);
            var classroomId = await start.ExecuteScalarAsync(cancellationToken);
            if (classroomId is null)
            {
                await transaction.RollbackAsync(cancellationToken);
                return OperationResult.Failure("Choose one of your schedules for today that has not already started.");
            }

            await SetClassroomStatusAndLogAsync(connection, transaction, (long)classroomId, teacherAccountId, "Cooling", "ClassStarted", null, cancellationToken);
            await transaction.CommitAsync(cancellationToken);
            return OperationResult.Success();
        }
        catch (PostgresException exception) when (exception.SqlState == PostgresErrorCodes.UniqueViolation)
        {
            await transaction.RollbackAsync(cancellationToken);
            return OperationResult.Failure("This teacher already has an active class.");
        }
        catch
        {
            await transaction.RollbackAsync(cancellationToken);
            throw;
        }
    }

    public async Task<OperationResult> EndClassAsync(long teacherAccountId, CancellationToken cancellationToken = default)
    {
        await using var connection = await OpenConnectionAsync(cancellationToken);
        await using var transaction = await connection.BeginTransactionAsync(cancellationToken);
        try
        {
            await using var end = connection.CreateCommand();
            end.Transaction = transaction;
            end.CommandText = @"
                WITH active_log AS (
                    SELECT id FROM attendance_logs
                    WHERE teacher_account_id = @teacherId AND time_out_utc IS NULL
                    ORDER BY time_in_utc DESC LIMIT 1
                )
                UPDATE attendance_logs log
                SET time_out_utc = CURRENT_TIMESTAMP, status = 'Completed'
                FROM active_log
                WHERE log.id = active_log.id
                RETURNING log.classroom_id;";
            end.Parameters.AddWithValue("@teacherId", NpgsqlDbType.Bigint, teacherAccountId);
            var classroomId = await end.ExecuteScalarAsync(cancellationToken);
            if (classroomId is null)
            {
                await transaction.RollbackAsync(cancellationToken);
                return OperationResult.Failure("There is no active class attendance record to end.");
            }

            await SetClassroomStatusAndLogAsync(connection, transaction, (long)classroomId, teacherAccountId, "Off", "ClassEnded", null, cancellationToken);
            await transaction.CommitAsync(cancellationToken);
            return OperationResult.Success();
        }
        catch
        {
            await transaction.RollbackAsync(cancellationToken);
            throw;
        }
    }

    public async Task<IReadOnlyList<TeacherRequestEntry>> GetTeacherRequestsAsync(long? teacherAccountId = null, CancellationToken cancellationToken = default)
    {
        var items = new List<TeacherRequestEntry>();
        await using var connection = await OpenConnectionAsync(cancellationToken);
        await using var command = connection.CreateCommand();
        command.CommandText = @"
            SELECT request.id, request.teacher_account_id, teacher.display_name, request.request_type,
                   request.request_date, request.reason, request.needs_substitute,
                   request.substitute_teacher_account_id, substitute.display_name, request.status,
                   request.admin_response, request.created_utc, request.reviewed_utc
            FROM teacher_requests request
            INNER JOIN user_accounts teacher ON teacher.id = request.teacher_account_id
            LEFT JOIN user_accounts substitute ON substitute.id = request.substitute_teacher_account_id
            WHERE (@teacherId IS NULL OR request.teacher_account_id = @teacherId)
            ORDER BY request.created_utc DESC;";
        command.Parameters.AddWithValue("@teacherId", NpgsqlDbType.Bigint, (object?)teacherAccountId ?? DBNull.Value);
        await using var reader = await command.ExecuteReaderAsync(cancellationToken);
        while (await reader.ReadAsync(cancellationToken))
        {
            items.Add(new TeacherRequestEntry(reader.GetInt64(0), reader.GetInt64(1), reader.GetString(2), reader.GetString(3), reader.GetFieldValue<DateOnly>(4), reader.GetString(5), reader.GetBoolean(6), reader.IsDBNull(7) ? null : reader.GetInt64(7), reader.IsDBNull(8) ? null : reader.GetString(8), reader.GetString(9), reader.IsDBNull(10) ? null : reader.GetString(10), reader.GetFieldValue<DateTimeOffset>(11), reader.IsDBNull(12) ? null : reader.GetFieldValue<DateTimeOffset>(12)));
        }
        return items;
    }

    public async Task<OperationResult> SubmitTeacherRequestAsync(long teacherAccountId, SubmitTeacherRequest request, CancellationToken cancellationToken = default)
    {
        await using var connection = await OpenConnectionAsync(cancellationToken);
        await using var command = connection.CreateCommand();
        command.CommandText = @"
            INSERT INTO teacher_requests (teacher_account_id, request_type, request_date, reason, needs_substitute)
            VALUES (@teacherId, @type, @date, @reason, @needsSubstitute);";
        command.Parameters.AddWithValue("@teacherId", NpgsqlDbType.Bigint, teacherAccountId);
        command.Parameters.AddWithValue("@type", NpgsqlDbType.Varchar, request.RequestType);
        command.Parameters.AddWithValue("@date", NpgsqlDbType.Date, request.RequestDate);
        command.Parameters.AddWithValue("@reason", NpgsqlDbType.Varchar, request.Reason);
        command.Parameters.AddWithValue("@needsSubstitute", NpgsqlDbType.Boolean, request.NeedsSubstitute);
        try
        {
            await command.ExecuteNonQueryAsync(cancellationToken);
            return OperationResult.Success();
        }
        catch (PostgresException exception) when (exception.SqlState == PostgresErrorCodes.UniqueViolation)
        {
            return OperationResult.Failure("A pending request of this type already exists for that date.");
        }
    }

    public async Task<OperationResult> ReviewTeacherRequestAsync(long adminAccountId, ReviewTeacherRequest request, CancellationToken cancellationToken = default)
    {
        await using var connection = await OpenConnectionAsync(cancellationToken);
        await using var transaction = await connection.BeginTransactionAsync(cancellationToken);
        try
        {
            long requesterId;
            DateOnly requestDate;
            string requestType;
            bool needsSubstitute;
            await using (var read = connection.CreateCommand())
            {
                read.Transaction = transaction;
                read.CommandText = @"
                    SELECT teacher_account_id, request_date, request_type, needs_substitute
                    FROM teacher_requests WHERE id = @id AND status = 'Pending' FOR UPDATE;";
                read.Parameters.AddWithValue("@id", NpgsqlDbType.Bigint, request.RequestId);
                await using var reader = await read.ExecuteReaderAsync(cancellationToken);
                if (!await reader.ReadAsync(cancellationToken))
                {
                    await transaction.RollbackAsync(cancellationToken);
                    return OperationResult.Failure("The request is no longer pending.");
                }
                requesterId = reader.GetInt64(0);
                requestDate = reader.GetFieldValue<DateOnly>(1);
                requestType = reader.GetString(2);
                needsSubstitute = reader.GetBoolean(3);
            }

            if (requestDate < DateOnly.FromDateTime(DateTime.UtcNow))
            {
                await transaction.RollbackAsync(cancellationToken);
                return OperationResult.Failure("This request can no longer be approved because its date has passed.");
            }

            if (request.Status == "Approved" && requestType == "Leave" && needsSubstitute)
            {
                if (request.SubstituteTeacherAccountId is not long substituteId || substituteId == requesterId)
                {
                    await transaction.RollbackAsync(cancellationToken);
                    return OperationResult.Failure("Assign a different active teacher as the substitute.");
                }

                await using var substitute = connection.CreateCommand();
                substitute.Transaction = transaction;
                substitute.CommandText = @"
                    SELECT EXISTS(
                        SELECT 1 FROM user_accounts
                        WHERE id = @substituteId AND role = 'Teacher' AND is_active = TRUE
                    );";
                substitute.Parameters.AddWithValue("@substituteId", NpgsqlDbType.Bigint, substituteId);
                if (!((bool)(await substitute.ExecuteScalarAsync(cancellationToken) ?? false)))
                {
                    await transaction.RollbackAsync(cancellationToken);
                    return OperationResult.Failure("Assign a different active teacher as the substitute.");
                }

                await using var conflict = connection.CreateCommand();
                conflict.Transaction = transaction;
                conflict.CommandText = @"
                    SELECT EXISTS(
                        SELECT 1
                        FROM class_schedules original
                        INNER JOIN class_schedules substitute
                            ON substitute.teacher_account_id = @substituteId
                           AND substitute.schedule_date = original.schedule_date
                           AND substitute.start_time < original.end_time
                           AND substitute.end_time > original.start_time
                        WHERE original.original_teacher_account_id = @teacherId
                          AND original.schedule_date = @date
                    );";
                conflict.Parameters.AddWithValue("@substituteId", NpgsqlDbType.Bigint, substituteId);
                conflict.Parameters.AddWithValue("@teacherId", NpgsqlDbType.Bigint, requesterId);
                conflict.Parameters.AddWithValue("@date", NpgsqlDbType.Date, requestDate);
                if ((bool)(await conflict.ExecuteScalarAsync(cancellationToken) ?? false))
                {
                    await transaction.RollbackAsync(cancellationToken);
                    return OperationResult.Failure("The selected substitute already has an overlapping schedule.");
                }

                await using var assign = connection.CreateCommand();
                assign.Transaction = transaction;
                assign.CommandText = @"
                    UPDATE class_schedules
                    SET teacher_account_id = @substituteId
                    WHERE original_teacher_account_id = @teacherId AND schedule_date = @date;";
                assign.Parameters.AddWithValue("@substituteId", NpgsqlDbType.Bigint, substituteId);
                assign.Parameters.AddWithValue("@teacherId", NpgsqlDbType.Bigint, requesterId);
                assign.Parameters.AddWithValue("@date", NpgsqlDbType.Date, requestDate);
                await assign.ExecuteNonQueryAsync(cancellationToken);
            }

            await using var update = connection.CreateCommand();
            update.Transaction = transaction;
            update.CommandText = @"
                UPDATE teacher_requests
                SET status = @status, substitute_teacher_account_id = @substituteId,
                    admin_response = @response, reviewed_by_account_id = @adminId, reviewed_utc = CURRENT_TIMESTAMP
                WHERE id = @id AND status = 'Pending';";
            update.Parameters.AddWithValue("@status", NpgsqlDbType.Varchar, request.Status);
            update.Parameters.AddWithValue("@substituteId", NpgsqlDbType.Bigint, (object?)request.SubstituteTeacherAccountId ?? DBNull.Value);
            update.Parameters.AddWithValue("@response", NpgsqlDbType.Varchar, (object?)request.AdminResponse ?? DBNull.Value);
            update.Parameters.AddWithValue("@adminId", NpgsqlDbType.Bigint, adminAccountId);
            update.Parameters.AddWithValue("@id", NpgsqlDbType.Bigint, request.RequestId);
            if (await update.ExecuteNonQueryAsync(cancellationToken) != 1)
            {
                await transaction.RollbackAsync(cancellationToken);
                return OperationResult.Failure("The request is no longer pending.");
            }

            await transaction.CommitAsync(cancellationToken);
            return OperationResult.Success();
        }
        catch (PostgresException exception) when (exception.SqlState == PostgresErrorCodes.ExclusionViolation)
        {
            await transaction.RollbackAsync(cancellationToken);
            return OperationResult.Failure("The selected substitute already has an overlapping schedule.");
        }
        catch
        {
            await transaction.RollbackAsync(cancellationToken);
            throw;
        }
    }

    public async Task<IReadOnlyList<SupportTicketEntry>> GetSupportTicketsAsync(long? teacherAccountId = null, CancellationToken cancellationToken = default)
    {
        var items = new List<SupportTicketEntry>();
        await using var connection = await OpenConnectionAsync(cancellationToken);
        await using var command = connection.CreateCommand();
        command.CommandText = @"
            SELECT ticket.id, ticket.teacher_account_id, teacher.display_name, ticket.category, ticket.details,
                   ticket.status, ticket.admin_response, ticket.created_utc, ticket.resolved_utc
            FROM support_tickets ticket INNER JOIN user_accounts teacher ON teacher.id = ticket.teacher_account_id
            WHERE (@teacherId IS NULL OR ticket.teacher_account_id = @teacherId)
            ORDER BY ticket.created_utc DESC;";
        command.Parameters.AddWithValue("@teacherId", NpgsqlDbType.Bigint, (object?)teacherAccountId ?? DBNull.Value);
        await using var reader = await command.ExecuteReaderAsync(cancellationToken);
        while (await reader.ReadAsync(cancellationToken))
        {
            items.Add(new SupportTicketEntry(reader.GetInt64(0), reader.GetInt64(1), reader.GetString(2), reader.GetString(3), reader.GetString(4), reader.GetString(5), reader.IsDBNull(6) ? null : reader.GetString(6), reader.GetFieldValue<DateTimeOffset>(7), reader.IsDBNull(8) ? null : reader.GetFieldValue<DateTimeOffset>(8)));
        }
        return items;
    }

    public async Task<OperationResult> SubmitSupportTicketAsync(long teacherAccountId, SubmitSupportTicket request, CancellationToken cancellationToken = default)
    {
        await using var connection = await OpenConnectionAsync(cancellationToken);
        await using var command = connection.CreateCommand();
        command.CommandText = "INSERT INTO support_tickets (teacher_account_id, category, details) VALUES (@teacherId, @category, @details);";
        command.Parameters.AddWithValue("@teacherId", NpgsqlDbType.Bigint, teacherAccountId);
        command.Parameters.AddWithValue("@category", NpgsqlDbType.Varchar, request.Category);
        command.Parameters.AddWithValue("@details", NpgsqlDbType.Varchar, request.Details);
        await command.ExecuteNonQueryAsync(cancellationToken);
        return OperationResult.Success();
    }

    public async Task<OperationResult> ReviewSupportTicketAsync(long adminAccountId, ReviewSupportTicket request, CancellationToken cancellationToken = default)
    {
        await using var connection = await OpenConnectionAsync(cancellationToken);
        await using var command = connection.CreateCommand();
        command.CommandText = @"
            UPDATE support_tickets
            SET status = @status, admin_response = @response, reviewed_by_account_id = @adminId, resolved_utc = CURRENT_TIMESTAMP
            WHERE id = @id AND status = 'Open';";
        command.Parameters.AddWithValue("@status", NpgsqlDbType.Varchar, request.Status);
        command.Parameters.AddWithValue("@response", NpgsqlDbType.Varchar, (object?)request.AdminResponse ?? DBNull.Value);
        command.Parameters.AddWithValue("@adminId", NpgsqlDbType.Bigint, adminAccountId);
        command.Parameters.AddWithValue("@id", NpgsqlDbType.Bigint, request.TicketId);
        return await command.ExecuteNonQueryAsync(cancellationToken) == 1
            ? OperationResult.Success()
            : OperationResult.Failure("The ticket is no longer open.");
    }

    public async Task<IReadOnlyList<TemperatureLogEntry>> GetTemperatureLogsAsync(long? classroomId = null, CancellationToken cancellationToken = default)
    {
        var items = new List<TemperatureLogEntry>();
        await using var connection = await OpenConnectionAsync(cancellationToken);
        await using var command = connection.CreateCommand();
        command.CommandText = @"
            SELECT log.id, log.classroom_id, classroom.name, log.measured_temperature, log.target_temperature,
                   log.event_type, log.notes, log.recorded_utc
            FROM temperature_logs log INNER JOIN classrooms classroom ON classroom.id = log.classroom_id
            WHERE (@classroomId IS NULL OR log.classroom_id = @classroomId)
            ORDER BY log.recorded_utc DESC
            LIMIT 100;";
        command.Parameters.AddWithValue("@classroomId", NpgsqlDbType.Bigint, (object?)classroomId ?? DBNull.Value);
        await using var reader = await command.ExecuteReaderAsync(cancellationToken);
        while (await reader.ReadAsync(cancellationToken))
        {
            items.Add(new TemperatureLogEntry(reader.GetInt64(0), reader.GetInt64(1), reader.GetString(2), reader.IsDBNull(3) ? null : reader.GetDecimal(3), reader.IsDBNull(4) ? null : reader.GetInt32(4), reader.GetString(5), reader.IsDBNull(6) ? null : reader.GetString(6), reader.GetFieldValue<DateTimeOffset>(7)));
        }
        return items;
    }

    public async Task<OperationResult> SetTemperatureAsync(long actorAccountId, SetTemperatureRequest request, CancellationToken cancellationToken = default)
    {
        await using var connection = await OpenConnectionAsync(cancellationToken);
        await using var transaction = await connection.BeginTransactionAsync(cancellationToken);
        try
        {
            var status = request.EventType == "HardShutdown" ? "Off" : request.EventType == "EmergencyOverride" ? "Override" : "Cooling";
            await using var update = connection.CreateCommand();
            update.Transaction = transaction;
            update.CommandText = @"
                UPDATE classrooms
                SET target_temperature = @targetTemperature, current_temperature = @targetTemperature, ac_status = @status
                WHERE id = @classroomId AND is_active = TRUE
                RETURNING id;";
            update.Parameters.AddWithValue("@targetTemperature", NpgsqlDbType.Integer, request.TargetTemperature);
            update.Parameters.AddWithValue("@status", NpgsqlDbType.Varchar, status);
            update.Parameters.AddWithValue("@classroomId", NpgsqlDbType.Bigint, request.ClassroomId);
            if (await update.ExecuteScalarAsync(cancellationToken) is null)
            {
                await transaction.RollbackAsync(cancellationToken);
                return OperationResult.Failure("The active classroom was not found.");
            }

            await InsertTemperatureLogAsync(connection, transaction, request.ClassroomId, actorAccountId, request.EventType, request.TargetTemperature, request.Notes, cancellationToken);
            await transaction.CommitAsync(cancellationToken);
            return OperationResult.Success();
        }
        catch
        {
            await transaction.RollbackAsync(cancellationToken);
            throw;
        }
    }

    public async Task ResetSystemToFirstAccessAsync(DefaultAdminOptions defaultAdmin, string passwordHash, CancellationToken cancellationToken = default)
    {
        await using var connection = await OpenConnectionAsync(cancellationToken);
        await using var transaction = await connection.BeginTransactionAsync(cancellationToken);
        try
        {
            await using var reset = connection.CreateCommand();
            reset.Transaction = transaction;
            reset.CommandText = @"
                TRUNCATE TABLE
                    temperature_logs, attendance_logs, teacher_requests, support_tickets,
                    class_schedules, classrooms, password_reset_tokens, fingerprint_templates, user_accounts
                RESTART IDENTITY CASCADE;";
            await reset.ExecuteNonQueryAsync(cancellationToken);
            await SeedDefaultAdminAsync(connection, defaultAdmin, passwordHash, cancellationToken, transaction);
            await transaction.CommitAsync(cancellationToken);
        }
        catch
        {
            await transaction.RollbackAsync(cancellationToken);
            throw;
        }
    }

    private async Task<IReadOnlyList<ScheduleDirectoryEntry>> ReadSchedulesAsync(long? teacherAccountId, CancellationToken cancellationToken)
    {
        var items = new List<ScheduleDirectoryEntry>();
        await using var connection = await OpenConnectionAsync(cancellationToken);
        await using var command = connection.CreateCommand();
        command.CommandText = @"
            SELECT schedule.id, schedule.teacher_account_id, teacher.display_name,
                   COALESCE(schedule.original_teacher_account_id, schedule.teacher_account_id), original_teacher.display_name,
                   classroom.id, classroom.name, classroom.capacity, schedule.subject_name,
                   schedule.schedule_date, schedule.start_time, schedule.end_time
            FROM class_schedules schedule
            INNER JOIN user_accounts teacher ON teacher.id = schedule.teacher_account_id
            INNER JOIN user_accounts original_teacher ON original_teacher.id = COALESCE(schedule.original_teacher_account_id, schedule.teacher_account_id)
            INNER JOIN classrooms classroom ON classroom.id = schedule.classroom_id
            WHERE (@teacherId IS NULL OR schedule.teacher_account_id = @teacherId)
            ORDER BY schedule.schedule_date, schedule.start_time, classroom.name;";
        command.Parameters.AddWithValue("@teacherId", NpgsqlDbType.Bigint, (object?)teacherAccountId ?? DBNull.Value);
        await using var reader = await command.ExecuteReaderAsync(cancellationToken);
        while (await reader.ReadAsync(cancellationToken))
        {
            items.Add(new ScheduleDirectoryEntry(reader.GetInt64(0), reader.GetInt64(1), reader.GetString(2), reader.GetInt64(3), reader.GetString(4), reader.GetInt64(5), reader.GetString(6), reader.GetInt32(7), reader.GetString(8), reader.GetFieldValue<DateOnly>(9), reader.GetFieldValue<TimeOnly>(10), reader.GetFieldValue<TimeOnly>(11)));
        }
        return items;
    }

    private static void AddClassroomParameters(NpgsqlCommand command, string name, int capacity, int targetTemperature)
    {
        command.Parameters.AddWithValue("@name", NpgsqlDbType.Varchar, name);
        command.Parameters.AddWithValue("@capacity", NpgsqlDbType.Integer, capacity);
        command.Parameters.AddWithValue("@targetTemperature", NpgsqlDbType.Integer, targetTemperature);
    }

    private static void AddScheduleParameters(NpgsqlCommand command, CreateScheduleRequest request)
    {
        command.Parameters.AddWithValue("@teacherId", NpgsqlDbType.Bigint, request.TeacherAccountId);
        command.Parameters.AddWithValue("@classroomId", NpgsqlDbType.Bigint, request.ClassroomId);
        command.Parameters.AddWithValue("@subject", NpgsqlDbType.Varchar, request.SubjectName);
        command.Parameters.AddWithValue("@date", NpgsqlDbType.Date, request.ScheduleDate);
        command.Parameters.AddWithValue("@startTime", NpgsqlDbType.Time, request.StartTime);
        command.Parameters.AddWithValue("@endTime", NpgsqlDbType.Time, request.EndTime);
    }

    private static async Task SetClassroomStatusAndLogAsync(NpgsqlConnection connection, NpgsqlTransaction transaction, long classroomId, long actorAccountId, string status, string eventType, string? notes, CancellationToken cancellationToken)
    {
        await using var update = connection.CreateCommand();
        update.Transaction = transaction;
        update.CommandText = "UPDATE classrooms SET ac_status = @status WHERE id = @id;";
        update.Parameters.AddWithValue("@status", NpgsqlDbType.Varchar, status);
        update.Parameters.AddWithValue("@id", NpgsqlDbType.Bigint, classroomId);
        await update.ExecuteNonQueryAsync(cancellationToken);
        await InsertTemperatureLogAsync(connection, transaction, classroomId, actorAccountId, eventType, null, notes, cancellationToken);
    }

    private static async Task InsertTemperatureLogAsync(NpgsqlConnection connection, NpgsqlTransaction transaction, long classroomId, long actorAccountId, string eventType, int? targetTemperature, string? notes, CancellationToken cancellationToken)
    {
        await using var log = connection.CreateCommand();
        log.Transaction = transaction;
        log.CommandText = @"
            INSERT INTO temperature_logs (classroom_id, actor_account_id, target_temperature, event_type, notes)
            VALUES (@classroomId, @actorId, @targetTemperature, @eventType, @notes);";
        log.Parameters.AddWithValue("@classroomId", NpgsqlDbType.Bigint, classroomId);
        log.Parameters.AddWithValue("@actorId", NpgsqlDbType.Bigint, actorAccountId);
        log.Parameters.AddWithValue("@targetTemperature", NpgsqlDbType.Integer, (object?)targetTemperature ?? DBNull.Value);
        log.Parameters.AddWithValue("@eventType", NpgsqlDbType.Varchar, eventType);
        log.Parameters.AddWithValue("@notes", NpgsqlDbType.Varchar, (object?)notes ?? DBNull.Value);
        await log.ExecuteNonQueryAsync(cancellationToken);
    }

    private static async Task ExecuteAsync(NpgsqlConnection connection, string sql, CancellationToken cancellationToken)
    {
        await using var command = connection.CreateCommand();
        command.CommandText = sql;
        await command.ExecuteNonQueryAsync(cancellationToken);
    }

    private static string CreateSecureToken() => Convert.ToBase64String(RandomNumberGenerator.GetBytes(32))
        .TrimEnd('=')
        .Replace('+', '-')
        .Replace('/', '_');

    private static string HashResetToken(string rawToken) => Convert.ToHexString(
        SHA256.HashData(Encoding.UTF8.GetBytes(rawToken))).ToLowerInvariant();

    private async Task<NpgsqlConnection> OpenConnectionAsync(CancellationToken cancellationToken)
    {
        var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync(cancellationToken);
        return connection;
    }

    private static async Task SeedDefaultAdminAsync(NpgsqlConnection connection, DefaultAdminOptions admin, string passwordHash, CancellationToken cancellationToken, NpgsqlTransaction? transaction = null)
    {
        await using var seed = connection.CreateCommand();
        seed.Transaction = transaction;
        seed.CommandText = @"
            INSERT INTO user_accounts (username, display_name, password_hash, role, is_default_admin)
            SELECT @username, 'System Administrator', @passwordHash, 'Admin', TRUE
            WHERE NOT EXISTS (SELECT 1 FROM user_accounts WHERE role = 'Admin')
            ON CONFLICT DO NOTHING;";
        seed.Parameters.AddWithValue("@username", NpgsqlDbType.Varchar, admin.Username.Trim());
        seed.Parameters.AddWithValue("@passwordHash", NpgsqlDbType.Varchar, passwordHash);
        await seed.ExecuteNonQueryAsync(cancellationToken);
    }

    private static readonly string[] FingerPositions =
    {
        "Right thumb", "Right index", "Right middle", "Right ring", "Right little",
        "Left thumb", "Left index", "Left middle", "Left ring", "Left little"
    };
}
